classDiagram
    class TxnBatch {
        UID batchId;
        List~Transaction~ transactions;
    }

    class CommitLog {
        UID batchId;
        Version CommitVersion;
        Version PreviousCommitVersion;
        List~int~ committed;
    }

    %% Relationship link with a label
    %% TxnBatch "1" .. "1" CommitLog : linked by batchId
    TxnBatch --> CommitLog : batchId